CREATE TABLE [dbo].[deliverable] (

	[id] varchar(8000) NULL, 
	[name_text] varchar(8000) NULL, 
	[description] varchar(8000) NULL, 
	[deliverable_type_id] varchar(8000) NULL, 
	[transacting_customer_display_name] varchar(8000) NULL, 
	[receive_customer_id] varchar(8000) NULL, 
	[receive_customer_display_name] varchar(8000) NULL, 
	[deliverable_state] varchar(8000) NULL, 
	[date_issued] datetime2(6) NULL, 
	[date_revised] datetime2(6) NULL, 
	[date_created] datetime2(6) NULL, 
	[date_last_updated] datetime2(6) NULL, 
	[products_covered] varchar(8000) NULL, 
	[is_legacy] int NULL, 
	[formatted_standards] varchar(8000) NULL, 
	[project_number] varchar(8000) NULL, 
	[date_withdrawn] datetime2(6) NULL, 
	[date_under_revision] datetime2(6) NULL, 
	[revision_project_number] varchar(8000) NULL, 
	[models] varchar(8000) NULL, 
	[engineering_resource_name] varchar(8000) NULL, 
	[reviewer_resource_name] varchar(8000) NULL, 
	[receiving_customer_code] varchar(8000) NULL, 
	[search_name] varchar(8000) NULL, 
	[issuing_organization_name] varchar(8000) NULL, 
	[responsible_organization_name] varchar(8000) NULL, 
	[reviewer_organization_name] varchar(8000) NULL, 
	[date_made_official] datetime2(6) NULL, 
	[date_expires] datetime2(6) NULL, 
	[date_hold] datetime2(6) NULL
);