table Dataflow_UUID
	lineageTag: 6a14489f-578c-4a3e-9d46-e8e0bf9ab645

	column Environment
		dataType: string
		lineageTag: 5b08fd50-8d4f-4bcd-aab7-d062bcbd3bb7
		summarizeBy: none
		sourceColumn: Environment

		annotation SummarizationSetBy = Automatic

	column Workspace
		dataType: string
		lineageTag: 9f0ee064-321b-4b26-b9bb-f26766ab7574
		summarizeBy: none
		sourceColumn: Workspace

		annotation SummarizationSetBy = Automatic

	column Dataflow
		dataType: string
		lineageTag: fa45007f-af4b-4fd6-a155-10a8b9d309e4
		summarizeBy: none
		sourceColumn: Dataflow

		annotation SummarizationSetBy = Automatic

	column UUID
		dataType: string
		lineageTag: dbbf2c79-80d4-4ac2-88e8-1244e3ba9824
		summarizeBy: none
		sourceColumn: UUID

		annotation SummarizationSetBy = Automatic

	partition Dataflow_UUID = m
		mode: import
		queryGroup: 'UUID Tables'
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("rVtbj1y5cf4rwj4lgAnwUrw9Clk5MRAD9mqTPBjGolgs2pPVzsij0cbJr89XrZE0p7tnut0tvegCqMhTrPouZM2f/vTdW/2Ff7xX/e433/14//FBPzzwqz++xt/+Re8fbtaN8IP+9IP+eqP/89P3v8W/Nw6h9FBdy3M48kFdH1qd76PkWoqX1L/7829einz3y/u7W719cI8Bl8d/nq5M9Y6ieMc9N+dJ5+KxegjjRMCP9/d6K//7aYODp++ShktJpiPNyQ2p2alKZpqh1bpOxfvwcPeL3n+KV1b2vXVybVHE/mJwXYp3LUxZq46WOL0c73t9d/Or3vN4px8e9zi5cYnL1VTUUZ/F8crLSazSQiop6ok9vvnbx5v3vyCJjwHDklZ4OJm5OMIuXZ81uVlK0BTbnKQvB/zd7Yf3Kg83d7ePe2QaNJA0l7kg5FyCDHB3rCKzpOSjnDiXP9zf/TdCPtbNKgFnuRxVzTiWikjIqJOQfB1+YpETO/zjx7tdLf7tI/7tU9BJeZaQuhMO4ojzdE1idn4kmqlgv3G+HPQH/XD38V70UzyfqFFJ1VWdyVFAFfUYyM2ka2Xko/R6Zrz/eLh5d/N/bAn9FLtGLjNVdiEQOypDXcM2XVoiI5Uap/LLsd/yL+/f6U8/3rP8/Lk6e0q1smKLTRE1Z3UcF04/eGyfY0aST0SVv+r8+O4xA9lje5Sj0zJQ7cLeDSzgYvU+hxDSnCcy+vaBbyffz8+lnmYki5CaR0pTHa4RJfx1FkbH0yqnPvsBWZSf7LfP/bOGzxQXQMhXwrnP5thzddmX4GXEIutE0P+6u//55vYv/4bDeoxZUTkBZ+SwX9RSzN0ZlGCj1AYzrZj9adz4/d3Ud4/FNHOcdarzuTYcOHLAaESHvclcoSlA5QRw/PsfPoWikKn5jrrkBtCts7tWNbqsCY2Y0FnxFKZ9Bt1Xb/XdY5+/+kHl7lZQp0/K1KfasuLsO1rBAQMY+I7e71rSal1WP1WmP+otf8alhE/taYoLa6L1kUmUZ66og+Y1MRfP8my0tyikcff3F8hIi8QS0UQMxHS0Kqp1hOxCHs3P2ijq8yl+En7LSL2OngmYvKKiZHGOANORnIbJVbXhEJ+vhCdRN7S04kipMbmaB2iutoVNr+WmhJVbAQKM5+H0adCn3BRqLehINFdawzCluNZXcRV/WuBAD7Y7I+ghQdWEQ28huFAa0Doip2PYbitNQi6GvkB6XwPvsdRKEsqMgMC2OmpAAddrsFuKzpOOsk75jKgHVDUo4qx3TYaupQ72GwWsEEdRKV1XPqvKNny1grQYF3QI9AkC94QiaN7VTh7YWGvz5xTBEdLy5OtaBJkzC3KLPbpe+3LoZRA3S0WbnRF5j7lCXxy6OEZakdrEYEIZSC0n5bWgKco/EvSAviKPNrEImgIcQ6EEN4BigNwRp6/dtxLPWOAYh62YOEcowFkMJIC/KAuAT1boIaiMlPM5ZbElMqhUYQZGlrojMpwkii64VcPyK9UgL0isJ0G3bFa0IBFQMc0PVBp6wbWZvSsFWAPk7NLDeVH3KY1aRwkjcqzL5BYouDOISGOtmdPIL8mDr5EPeU1CzAmd5xYtHFyVary2XEfreQFCxHhOK59NIJwgGOPcMYaliAXQgU6PSZIMEP7kc8r7KYvExboqVacV30ELKMoF6nZ1E44T3JKfhzl09fy42+9LRIJ2hxKJIP+VDUHQnbnjcMF2oLBR6nz+XLcrbLmkSpg+iDjgqG3dA6FjKviSKOBxrVj1zMAbOukafAGcQgcYTUuaDrKnYxlJq0MR+fm8nN6L+5RRNHkwfIMbq6ZSK5wdvBlWUPE9xxXGC22ziXtIKgy+z2ggV80wUkKmG9DEzcEd6rgOekFdb2Lv8UrwzIZ+bi0GCVR4i4GDdIVG7EuR/3Lmpg+oBYgMuRarE2/nZ+5qVAhZQBKEQSqwGc9j0yb0hl1KCpRGLU6aJxObJjEQtpWk6BIK1M8siyMEU0g66BvuL4cdeaMXI1hGUshpsqeynqeuTfAtx0ALQrlDCFH3FjdDynvqLi+FLAIptvi82joe94BmlhRsOpmyZ/OKkHWdq7g6G6Rv6WuGM9c46pYguaYHDHrbN6UCvkz4luwXvNkIvMbzQmEbfUM2ndB3EwCVejfwhiIbBHLEbnGe8M4QjmfG3fINpCb76K25PSpb4zDFBIGLo/DU1CNdZwfepxwP9wRZ3lzeYUgzvCuluqnRw5/gWOXMXB9xUwzFNAMguwcUjHSYHwZkUwm1jay9xedZ4DigniIehREYGppLYaBVi4d5R724uLSjU3NK+cwln3LPjGXRhHDoO0MMSYFORc6ghFMDaQh83S7q724fQC76s/3/N69//+qNbfYeVPPu1ev3798Z5zxu/f0dSOj2L6/+6fs3//nPL5BSiZR5NazVMrA4KKo1dGjbFbTOpPg9Xbv0lq1mhvAyfxKGfWzphtDBuxi7wFovaB26dsUNjaUUFGcG3g0DlNCyNX4DjQ0drfsKmRmuXnDjmNTH6qfd4aFJKUXwMZLsGqhCBwCGHnnzG+T0VMEO0wCw7g7tBzQiKp8+PjYhdAhEiLZv8PFPriRC8UUb1pmd4BfzTuaoutZyEojMKena8/1yZ8GEDkHTuR4AA5QBjJ1xyGVlqVlMwOVr1zqUGIAsHGR0AqJ6vG2qY7ggLLBcQNMlVy66pz0yjQXob0a2bFeQ1a71zIxX2KLA8GPXfuaBKGkE2KEG89XhcqmB0EasGcCH4p4B8J2uLZyNWvFc0lylOdZg10+AVx5YuQafG4sXfry7uHy9IzJmpFVLgH3wifGVHrAE50UuQHsNn3Cc/Vps2OobVGxoTYdLEdxBHU6JofGcrshTap2zr2+14IHwSQ3SOwt04BKQsd03waExyHiW4BfyTNe25jFFlBTuUiGwUoEwp9rUeFpcAF/ORjq8XouHW6nUoAxSA4smnbCjs+E72a6s4lgRfRS49msX3GooGOcYGCxGa+weMpBju84RQV0vRpNe3aHHxBXn3LtJqjyh3AjGDw4HHwszntFCvcxre+apTLEeLEFM7UBqESSWG127CyGS1hK9XM1rhyIvckLZenWhoXBBYEDbjg+F5u0m18nXeemib398/a9vXlJHHKb0DNRrwHYsnhi5JTV9XNAtk9Pl8PB18XO5vAKaYoz2sjWCvWJCfAKiXZGuCagJF/oNUrFVazmkOTy0aAKdo3chDVuVBpT0efCsc4m/fs2NXoN8yiIgVN09hjZTTh3iNPQ1JtHkeXmZPVly8/4K71QhtJ2PZI0kIB9fYJWDfX+eyMH1Sx4qCeQQy1YYGB+DWTqs2BI4VvOKGnJd36C297SEIGypUIDoqWlXdQG6FJaPBvVWUiJtFwv+L2se3p4PaCMZzWlq0SSxvfhwdV0J8kKh4ka5etWNngg40xl7t8dfSMMQO0RijK4w+CbH7n27GBu/rHhEUcRV4A/xffgye4KFQx+Af9h0kCuEDNHlBP9l3a2mkCYBLNNcTYYLxS8HwbRcZQ8PPFmLXp/cF1QFK5RamM6Tt361i4mcJ47aA5Qa7F6+mPu+LH9MV+TVzR+r2123UIGW6uy7yxwAFKtGpott89eFN8qiFG4xVxD7tO4xGYVvjcCmqUQrcH58DLtqya228JVKGtDD6BrLbwMdpZicvbwLfqXWv8FnHqqLKXmspvZkYlc3WaGNGb6OCvnM3LT560Hxqb6gCLHkU7QxGmvZ0e3urznQPXxeQXnp9Wx75PEi1zC0L4i1alfGASisdhmzqozAiUa40M+9oCwgJWrL6Je1DHx9xWfqINc7pMZIorlcmNxDDl95webM4gaoG0W7lt13Mtit2mvxjKNd8YEb7pbQOEQ48Jy93bUA+Eaa3kGVBvipOHu68Aj/EaHUqQ+7AnT22ThRYGGfSV0ZpsbhRqCNr/jgzVtGKd4zQ4llsBsNcA3PQq6WxDkNmr5dqI+O3z1UheZET7QIl0o9QvvHXFyhqcvnrJ3jxcvtz3upH6OiHadJIYKjsFtJuEWIJK402syXl+iBQlhcQpvdihQCm1AsbmjxkAmBRx7S26W8eaAMQk8po0a5WOslwp9Szw6+tEDSU63jwpuNZxRBhWgtkHU87Jo6Brg0FIdblOETF2kZF+L3gRKImsOIQGvpRhWkQDG70q01QmHxEN8uFJQvKgCUwoLUyFgWMAoFsHvZtOvsCDxHy0PkXbzsMeYnSQp7G9zcjTcQlh6Z8J1tpGWjfmVc/p17dwmT14J8Bftm2HsBjPa4EjwwhHusZUm4kPEPmT5gqUIl2DuJvS6gsVEzHuqiAdI4rUGXo+exETf4+KJiUwADONlKdxzsdoZGoYCz5EsZfo/ZQ1jcalZXO/QZxWJsJ1CMsPYsMZjtunihQ0a3h9rRV3Sxiz3BNTPK6L3laSmkVAur7b/SvPn7e72/MfTjdy/wdhpqF1jLQebb5K8OxwZTcMPo5tRboIP3rP3QW3ZmUV+mbbGuaS8wO3mXUdrVrx6L6Di52e2z/Ror2TQyWB+UJBGYKpFgSCJwVIOH0DgZcPOeQbF2GdDZ08ZGIqO9oR3c5CIe7MM1HIyN7AU8ZDLShHKHK4OwRAtLXlAKlkj1JB22GGd1Iuj+C/2E0TGCSl5sm9CrTQEKU0OCKxuSysEQyl7EA1ZSFCxoCEAjwjagAK4YNgvXO/I4Y87h4G10L+aWe/Bh3PHVIDm7mazqRunqoqBDwsxouVN7PDaiHFfm3rwzr2fPn8n1BLrOHv5rUvfY+ImoWx6BpogSoeCSjfvRmAo1PIaL2lBaOVVgxbkBD/2ikl17LJSTjTvkYYi6s21Teikz0OED+V7wo7fMOaLR23KQsyh7jsG1YVO2OD58DMd4OF6zH3aD/BUNHRgSXYlths5DjPjQIdGhsqbyDKf3uYfvAyWjwayxjX6TzadD6LsqMZaJI8zj5BYPUVxaBl57m/epYChvD6o+iZMEk0YZcl8OBgP2oj7FatEi0GDBpbyz8x7c2gDYgRQifo256GCyYy/cEY/lS55q843Dxl1nsXER+DtoA2m8oM5fGAP4Xn+9e/8B//L647x5+DxM1XrO2FYuxTxNFOzSZklx0N0jESDt0wGfHdVK3oeVqws26Ut2GQlbRi6RUC4+J50HmHwk+hboaXmPxE5Qn/1USwk2CgFUKVymzYNr9M/PWXwNusH6OSnVEBhaedngA6LDbwHrU/URDpNjPScNG7gHKoPMgCGamv2AAtltL/ILM0Utd/Wsz4/nf4l5iPhz9Rw4s9kwJDXBLw0bc5xhps7US31haO9L3D3Qp4Wz76gk+B9Ua7ekopnczDkW0gysPaOwDt1IEw8mDpAMEO5oIjTBZHbB28jzWgGIezrsBvqVC4nvNj5n401gTtfMhUjJvWaJKIrn53e+hDyC/qH2ATmsLmSj0wIVwR6WF2AtNdVCXZ6fK/wSeG/UF2IXpAli2r2gUWifjISI2m0MfIs8Pzt2GPOAAyRwqoLUQqvsegFcXVAaI/QFCpwQ92fU2PFLwYL6ouySTACDTRg20Bm4sM8O4hEKZ+x8ywSkcU3wiPPD2w/AMLypPUsUH2ZtJXKQ52f/vsbckkGWHGpLzU2zaSQFuhufbj/JYQJmaqxnYMwRPkBi41g+uJjsuRU15zqOyyWbHNaRC8j3dOCnlDBUGPgynd1o2LvxTqJi5za2WGJmfmHA9EvEIzq9AvMiSMu6zX4QqNkFrnfKXmbtzGTDfn/+fw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Environment = _t, Workspace = _t, Dataflow = _t, UUID = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Environment", type text}, {"Workspace", type text}, {"Dataflow", type text}, {"UUID", type text}})
				in
				  #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

