table Workspace_UUID
	lineageTag: 29132b94-863f-41ba-8099-3b8ece6253ae

	column Environment
		dataType: string
		lineageTag: 8123fd7b-13fc-4709-a2b6-b312e5c5d525
		summarizeBy: none
		sourceColumn: Environment

		annotation SummarizationSetBy = Automatic

	column Workspace
		dataType: string
		lineageTag: 7a29e41d-18a7-4d17-8c30-fad08681055c
		summarizeBy: none
		sourceColumn: Workspace

		annotation SummarizationSetBy = Automatic

	column UUID
		dataType: string
		lineageTag: c82a8fc4-2185-4508-9e64-f0656ebc73f1
		summarizeBy: none
		sourceColumn: UUID

		annotation SummarizationSetBy = Automatic

	partition Workspace_UUID = m
		mode: import
		queryGroup: 'UUID Tables'
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("nZJPaxwxDMW/yjCnFiLwf1vHhQylh0LbXXoJe5BsuSzdzAyzk5KPX22PpbnkYLCF+OnpPT89jUd5ptMmMj6Mp+1ll9tOw7eDvqQL2l48lFYcBJcSFCYLxtccGmOxPoznh/8TjjQ3Xl61FMh0HzoBU/MQxBZAQoFqGraI7Lxrb2K+bkt7qftlmbVKtmd0JoONESFgN8BslOldyt5bG2v+lzS9rrJdnmXe6XpHZCqqJQJJrxAsoiIaQ3RsqPdia+1/EZ/nXbZdft3FTIcvw3SVum+XStfhsK5XvdxF3Ybvsi7bfpl/Dh8epx8ftb2Yal0JAnoKBMYElKIAckY1rXXJ5r0jjqfDp+k+pEbGrimAcdxAN0LA5Cqk4owtUq2we98QbWRhH2IIIKkyBBI1CY3Ce23Jt5ptsm8m9ii/l/WmFVQ/0anVJbFo7qUBJ8rAQb9V9poj1fF8/gM=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Environment = _t, Workspace = _t, UUID = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Environment", type text}, {"Workspace", type text}, {"UUID", type text}})
				in
				  #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

