table Dataflow_UUID
	lineageTag: 15f7f707-4dea-4eeb-ab9b-f5e8229a8f58

	column Environment
		dataType: string
		lineageTag: a012d8b0-b44b-470d-9743-8d4e87df45e1
		summarizeBy: none
		sourceColumn: Environment

		annotation SummarizationSetBy = Automatic

	column Workspace
		dataType: string
		lineageTag: 655b245b-47a3-42bf-ba40-e47f9e603f5b
		summarizeBy: none
		sourceColumn: Workspace

		annotation SummarizationSetBy = Automatic

	column Dataflow
		dataType: string
		lineageTag: 49fab6a9-0a90-402c-8678-3d0a48d2d1ac
		summarizeBy: none
		sourceColumn: Dataflow

		annotation SummarizationSetBy = Automatic

	column UUID
		dataType: string
		lineageTag: 7928aa94-2c80-4293-a149-ea33a2147116
		summarizeBy: none
		sourceColumn: UUID

		annotation SummarizationSetBy = Automatic

	partition Dataflow_UUID = m
		mode: import
		queryGroup: UUID_Table
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("rVtbb1w5cv4rg3lKgCXAIou3RyPjTfYhQHbsJA+LxaBIFjfK2JJXlieb/Pp81dbIOn2RervHL74ALvIUq74LWfrTn75/px/l/b3q97/7/v39lwf9/CDf/fEN/vZPev9ws26GPOhPP+ovN/o/P/3we/x7FaLcqLiaZnfsSV3rWpxvPaeSsx+xff/n370U+e7jp7tbvX1wjwGXx3+eLk/1jsPwTlqqzrPOJX01ov5KwC/393o7/vfrBrtM30bsLsYxHWuKro+SnOpIwpNqKeu1eJ8f7j7q/dd4eSXfamNXFwfsL5BrI3tXaY61Sq9R4svxftAPN7/ovfQP+vlxj1Oq5LBciVkdt5mdrLTcCGVUijkGfWWPb//65ebTRyTxMSCtUbN0N2bKjrFL12aJbuZMGkOdk/XlgH+4/fxJx8PN3e3jHoU7dyTNJckIOddABqQ50TFmjtGH8cq5/Nv93X8j5GPdrEw4y+W4aMKxFERCRt2g6Ev3E4u8ssM/frnb1eJfv+DfvgadnGam2NwQGo4lTVdHSM73yDNm7DfMl4P+qJ/vvtwP/RrPR66cY3FFZ3RMqKIWiN2MulZCPnIrZ8b794ebDzf/J5bQr7FLkDxjEUfE4jh3dRXbdHGN0WMuYaq8HPudfPz0QX96fy/j51+rs8VYiii2WBVRU1InYeH0yWP7EhKS/ErU8V86v3x4zEDy2B6n4DR3VPsQ7zoWcKF4n4gozvlKRt89yO2U+/lrqccZ2CLE6pHSWLqrzBF/nVnQ8bzya5/9gCyOn+y3X/tndZ84LICQL4xzn9WJl+KSz+RHD3msV4L+5939zze3f/kXHNZjzILKIZyRw35RSyE1Z1CCjXLtIrxC8i/HfPNl3jwWpmZdnHQ6QERz3D2qfZXpvEQk2PuKxno52Hu9lV+7O8qYLc7haE00EPaDQ04F2axeo0j2cjraOxxHv/vbdn9T2C+tyXUGPrK3YqSljnRX5UVqDWdEPEUSmkfIAcUtQDLHq6CKOiVHqVc/S+WgfE74LVO00ltiYOUKapueCSDXo1OaUlQrUO70CT2LuqGLFXqMVdiV1EE/pS5sei03B61UMzqzn4a550GfcwaVktEpKPq4uvV6drWt7Ar+tMBNHix0RtAjxBFDlAT8kAIoZmAwzq2CjPpi36avw5+T2D32WHFQngHQVK1aI+q2ri5uKTpitILiS2dEPaCQzgFnXSoygG7iBlbqGWgdetaRm650Vt1ueGTRqCEs6APoBgRuEUWADJTGHphVSvXnFMERMvHsy0IancwMhsIeXSttOY0RhCqjrHpa2XyLvMco1JZQG06QVqQ2ChhqdKRWospa4Pr89wQ9oJUgvU4sgqYA9jNlcn0uAhT2MH1pvuZzOvkYtyyrtQBlNrPBDnARZVHZJYVOAfvHlM4piy3BQD0OEQ0ulx3B4CRRdORWoeVXLDRekD7Pgm5ZJmtGIqAuqu+otMmo4Jm8yxlYE0tto9F5UfephmtDCSNyKMtkEKixCQhCQylJYk8v0fa3yId8MyikiM5ziwG8XEYxvlmuofX8AEKEcFpXfgv8nCfCEl2Fi9OCuLyAapKhAlczgTXBHuk07KDL5pdd926pYkWUr4cOgICDwqgVetp0i1IXbj5BF5xOwCboSbZAT0MGBDDvSgYTaMHUcIJNBcwHOpqnD2+7wpYwyqDpaQyXa7J8eMBwiBnpCYPL1IJVzwy84Yym5DMw01XAG2o4TgfN0bDMiKtBjvh5WsvuxX1OGxr9alphhYpJxAJbBWOEFXT4lsKi/kJvbOIeMseqPuc2ILiLkSeKC7HBc7mnrrNBR/PpZt7E3iMP8iIGcW4tAdIXCPuOg3SZe2hLkf985qYP+AOwuwRY44a38zNr0wtUJHAH7B8zNP6Ze95QSI7EsZfsRvVsSs90BMLWHDWOzsTtzLI4wiKZR0NiYb0SBA8H+JIWQCUjUopTPOd1mp82wbdE0lkgm6F2rOds09DRnptLS6F9wHw1nGb+43EPuGSNjE1Hk9ViRg3arUkZrswqFd5nTTpzjaNWBbpqQnU6b/vmmEGKEd+S/IIx6iSrn1YD2+gbRmmMvptAvdiaITRkV2cwIHaL84RxhTo8M+6WVKAnxQdvze1R2Rq6ySKoWByF56oe6To78D6veFgXqPnq0g5DquFdzsVNDX5RxbGOM3N9xMoIZNEk8EAjFMxo0IsCHuBMpfakrYbTSmYT+zm7zJAXT1B121lDkDjaBh8wC3wIEHzANuyi/uH2AUivP9v/f/vmX797+wGtdw/c//Ddm0+fPhgBWI9/96N+ugMj3P7lu3/44e1//OOWdmKaUXqBYoRggBoD5TYoP9eBvYM7DoL7laud4qMcOMmq+LKaAMOkKFRqWHqRlhkVv8drl94S1UwQVuY/qFtqc0uoNPIuBFBvpgUtw9euuGGwGEmRSVAudfjImqznKxisa6/NF8hIunrBjSNSH4qfdneG/uQYQMVIsqtgCe3AFn6kzMsXPOQ8QQ8hfHADyPl491B6dzRkQOijvde4ctE9MkzcF7CoGvqLXUgVu+QxC1ggxkngAtKVKx6wZGW0HldI/gZvxRUI20NJLhJSPgl4EuuVa27o0wu87crVCSQgWKKjPTpWLuRTleGH9Gs78wiv9rgKBOhwPu6cL5oFep8dQQx0H83+XluxW8IVqP5atbsYPD6zQZ8LRIfTFWSOUuZs67da8ICJY4UWTAPCZEGysd1ywBcI2GFm8gt55msB4RhFR4WnUTB+zJDjcO5qxDEcZWiXytq9XtulW+6uoKpYwSRRJ0zQhLloYhcloa+APiIp7doFt6QOuxZIgK28+u5aGzm2S4QBj5OXoEmv7tBjbC8ptWYcnyakBMOJSLFDhQVMaKGW57U985yqrQczjenCaubZIFp60+aIAmvJwY+r0fZQdQSJKFuvjioKl5mBtg0fChHWTD+yL/PSRd+9f/PPb/cUAjwprGlAna4FhaDAvcaQ8UVSHyIz1HJxgz6td0ojCM3RElC2gkvwsVFwlqwmEDO6c0q8HI6+Lb5VCYni7B6KK84GUCiQJLWMChz0qcsscw1//ZobnQDaTmOAMnX3+FWNsRtEEbUFY8pT5uWF9GzJzXsb5HqBnHQ+sLUK7LvAbbtK9v1QhbNfv+ShVkAOsWyBZvaBzEVgxRrBoppWUEpl/QbVu6cWBsLmAtmFrpl2BUTQQ3AZULsNZjSy1ouF5tOah7eyHepn9Oo0Qk9DiqF0uxTXlCEgFGq+56tX3SgGwpnO0Jo99kFtUmiuERo3CxglheZ9vRj9nlY8ohnCykoV34cvsyc3mMIOgIczBH1CqjBfTuFP625Vw6iDwCPVFThaLOmXgyRaACUP2zVFs16f3Bd0gyi0GE3n2Vu/mhdOaeKoPcRahc1IF7Pb0/LHlENazVygup3D5wy11MQ3l4QAFKsE4YvN4beFN9ohZ6khwdaCzNA9JpTwrQHYNJV5kaTHR5arltyqB184xw7Fi66x/FYQQAzR2UvrwK9Y22/wmYf6YY7UV1W7irfbgqRQv8LQL5l9Eqla/fWg+FxBcIAc8jHY2IS1bG923VQdCJ2RA5SXXs9vRy7FU6GubUGOFXvfJKCw2pXDKqOTRO50oWPbaoc0WogBfdJKNnfGNs+SIQUDFH/lHOq8UF+/oBkgEkpN6Mu1DOR9QTq1s2sNIqLHoSlfeIiHWmGlBcM0s+uQCKaQll3lCVi02GvnDL1ensitRhhUhUIvLiVvdwkA2B6nd9C3BGcWZosXlsqBNtCcvRfp0FrgL+5gE5mZXclRUuw8fb1QAR2/PygKHYeqrwFOk1uAfg8pu8xTl09Jm4SLl9uf4FHfe0HDTRM7DFdgt2twfJBBUrjXmS4vjgMNsCRTnc3KA6KVcUyua/YQAiQd8rnVS5nxgPupxZhQHZKt6CM6DTlNDt4yQyZzKf3C24kTnF8gSzOEm3S7+wwEp4XicIsTvN5izf1ChD7g+qCJegAej2ZkwAqcssvCUgI0lPTh64WS8UWORyksiImEZQGU4Pjdc5ldywYgNpoNMu7iZY9xO4+osKjk5u5hnLF0T4zvrD0uG97K/fLv3LsPmLIWBCr4NcGiDwBYCyvCx0Kah5LXoAs5/ZDLCUtlzmSX78NGFLLVjId+qI3tsaLz5bh1bGgJXjzrsPfjDr1Sc3NCdsPCPTPhLOVSDt/jbqIltSR1pUGBccjGMwOaEPZcRiAzVhcvdMjZ9vrX2woutGHvOhXwnNF7y/NSiKVKq+6/Nrz92ye9vzH0kw8vMGbsapdQy0HI2yyndicGU/C76ObYKvHBI8l+6C0vylCfp22xrGl3+zsBl1Daxa8W8tD+6ma3b8Grr2jzpeBbUNIIwNQRGJYjAEeVPCj+1YCbm3IOpY0OJT1t4CAI2hus7abk4cE+UujgvX0v4CGTsUaUO3wXpCNaeKQFjrZEqufRYHxxVq8E3X/2nbAyRlDRD9smFGlVgMJUivBdfcR8ML6wF/GAlRQFCxoC0Iwh9uoNrug2RdUa8jhDSnTw4LYXc8s9+DBp+GqQnN0uFnU9N3VhoENoJrTca3s8NnQaVpJWvTM3Z29q0bUIuk4eDmty83w427cXdcsj0BRhBGinaINi3KdC7/buglaUVooFWHFuwENHqGwXGwvlZG/oqRui7ozZHC3nSXz46roX/OhNcQpo9LochCTKXgK5am904FfCx0gIhzMb+2E3yF/Q0CQQx8pi01ceYsRTgziGypoqk17f5x6+d5SMkplfG+ZlmziGxHZlhJAnjjD1V7d4iOKjJuC1tyGSAoby9lTn43AjwoZxgtAeB6/Ne1GfY/XQPKDByMW0M+we3FoB2MQK+bz6XHwwLrAX7oiL8jlNtcm4brMeM9sMAhwctMGostqML7wt/6C/3H36vLVLumpLCdtK2R5jVxjYJZEjHHTzSARI+/WAJ+d/ove0UnFkM6Js140wROwiD07Zp6jzAJOPRN8CPS/vkVg4PLWfU8hk7+tAlSx52oSvBn/68f5b0A3Wz8mxEAm08rLXdESH0wHWx+IDvJ2Eck4aNnAPVAaZAUM0Vhs5Z7vPRX7h3rimpl709MD1U8xDxJ+rJZKED+42LxLhl7oNyE2asQm3XOT0DMBT3D3Q54Wzb6gk+B9Ua7OkopncTClk1gSsPaOwDt1IHR5MTJAMEO5oIjTBFHHkbVh2LQLivh52A/0qmYdvNpNlMzNgThh8uJCRUytpBBTF6aGQp5BH0J9K65DD6igZnWaoCPF+GViPEkvmNk4Pqz0F3hsShdgFaYKYdq9gTPWrkRhD7b4FvmWcHkg6jHnAAYMkloHUQqvsegFcnVEandoCBU6I+zNq7Pi1X0Z9cXJxTACDja1V0Bm4sM0G4hlMZ+x8ywSsYU3wiPPd2480CLypPTxkT7PUHITG6YGybzG3ZJBGolJjddNsGo8M3Y1Ph5IsJmCmhnIGxhzhAyQ29OXJhWhPpqg513BcLtrMqfaUQb6vB35OCV2HAF+msxsNe/vdSVTs3GbhckgiL0wtPkU8otMLMC+AtKzb7Ec7ql3ReqfixyxNhG2C7M//Dw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Environment = _t, Workspace = _t, Dataflow = _t, UUID = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Environment", type text}, {"Workspace", type text}, {"Dataflow", type text}, {"UUID", type text}})
				in
				  #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

